name: Build Team React App


on:
  # push:
  #   branches: [main]  
  pull_request:
    branches: [main]

  workflow_dispatch:




jobs:
  Build:

    runs-on: self-hosted

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v5.0.0
        
      - name: Setup Node JS
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 24.9.0

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-artifact
          path: dist

  Deploy:
    needs: Build
    runs-on: self-hosted

    steps:
      - name: Deploy Using Docker Compose
        run: |
          cd $GITHUB_WORKSPACE
          docker compose down || true
          docker compose up -d --build
          docker ps
          docker logs team-app1
    
